name: runlah_flutter
description: Flutter version of RunLah

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # self-added dependencies
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.2
  cloud_firestore: ^2.0.0
  google_maps_flutter: ^2.0.3
  geolocator: ^7.0.3
  pedometer: ^3.0.0
  permission_handler: ^7.1.0
  intl: ^0.17.0 # for localisation
  fl_chart: ^0.36.0 # for bar chart
  light: ^2.0.0
  screen: ^0.0.5
  shared_preferences: ^2.0.5
  provider: ^5.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


